import React from "react"
import { Link } from "gatsby"

import Layout from "../../components/layout"
import SEO from "../../components/seo"

function generateName(e) {
  e.stopPropagation()
  var adjective = adjectives[Math.floor(Math.random() * adjectives.length)]
  var animal = animals[Math.floor(Math.random() * animals.length)]
  var obj = document.getElementById("companydisplay")

  obj.innerHTML = `<h3>${adjective} ${animal}<h3>`
  obj.style.display = "block"
}

const CompanyName = props => (
  <Layout>
    <div className="container">
      <center>
        <br />
        <b>
          <a onClick={generateName}>Click To Get Your Free Studio Name!</a>
        </b>
        <br />
        <br />
        <br />
        <br />
        <div id="companydisplay" className="companyContent"></div>
      </center>
    </div>
  </Layout>
)

export default CompanyName

const adjectives = [
  "Ugly",
  "Unique",
  "Untidy",
  "Upset",
  "Victorious",
  "Violent",
  "Vulgar",
  "Warm",
  "Weak",
  "Wealthy",
  "Wide",
  "Wise",
  "Witty",
  "Wonderful",
  "Worried",
  "Young",
  "Youthful",
  "Zealous",
  "Talented",
  "Tall",
  "Tasty",
  "Tense",
  "Terrible",
  "Terrific",
  "Thick",
  "Thin",
  "Tiny",
  "Tactful",
  "Tailor-made",
  "Take-charge",
  "Talented",
  "Tangible",
  "Tasteful",
  "Tasty",
  "Teachable",
  "Teeming",
  "Tempean",
  "Temperate",
  "Tenable",
  "Tenacious",
  "Tender",
  "Tender-hearted",
  "Terrific",
  "Testimonial",
  "Thankful",
  "Thankworthy",
  "Therapeutic",
  "Thorough",
  "Thoughtful",
  "Scintillating",
  "Secretive",
  "Selfish",
  "Serious",
  "Sharp",
  "Shiny",
  "Shocking",
  "Short",
  "Shy",
  "Silly",
  "Sincere",
  "Skinny",
  "Slim",
  "Slow",
  "Small",
  "Soft",
  "Spicy",
  "Spiritual",
  "Splendid",
  "Strong",
  "Successful",
  "Sweet",
  "Peaceful",
  "Pink",
  "Polite",
  "Poor",
  "Powerful",
  "Precious",
  "Pretty",
  "Proud",
  "Quick",
  "Quiet",
  "Rapid",
  "Rare",
  "Red",
  "Remarkable",
  "Responsible",
  "Rich",
  "Romantic",
  "Royal",
  "Rude",
  "Macho",
  "Magical",
  "Magnificent",
  "Massive",
  "Mature",
  "Mean",
  "Messy",
  "Modern",
  "Narrow",
  "Nasty",
  "Naughty",
  "Nervous",
  "New",
  "Noisy",
  "Nutritious",
  "Obedient",
  "Obese",
  "Obnoxious",
  "Old",
  "Overconfident",
  "Ignorant",
  "Illegal",
  "Imaginary",
  "Impolite",
  "Important",
  "Impossible",
  "Innocent",
  "Intelligent",
  "Interesting",
  "Jealous",
  "Jolly",
  "Juicy",
  "Juvenile",
  "Kind",
  "Large",
  "Legal",
  "Light",
  "Literate",
  "Little",
  "Lively",
  "Lonely",
  "Loud",
  "Lovely",
  "Lucky",
  "Gentle",
  "Glamorous",
  "Glorious",
  "Gorgeous",
  "Graceful",
  "Grateful",
  "Great",
  "Greedy",
  "Green",
  "Handsome",
  "Happy",
  "Harsh",
  "Healthy",
  "Heavy",
  "Helpful",
  "Hilarious",
  "Historical",
  "Horrible",
  "Hot",
  "Huge",
  "Humorous",
  "Hungry",
  "Fabulous",
  "Fair",
  "Faithful",
  "Famous",
  "Fancy",
  "Fantastic",
  "Fast",
  "Fearful",
  "Fearless",
  "Fertile",
  "Filthy",
  "Foolish",
  "Forgetful",
  "Friendly",
  "Funny",
  "Early",
  "Educated",
  "Efficient",
  "Elderly",
  "Elegant",
  "Embarrassed",
  "Empty",
  "Encouraging",
  "Enthusiastic",
  "Excellent",
  "Exciting",
  "Expensive",
  "Damaged",
  "Dangerous",
  "Dark",
  "Deep",
  "Defective",
  "Delicate",
  "Delicious",
  "Depressed",
  "Determined",
  "Different",
  "Dirty",
  "Disgusting",
  "Dry",
  "Dusty",
  "Daft",
  "Daily",
  "Dainty",
  "Damn",
  "Damning",
  "Damp",
  "Dampish",
  "Darkling",
  "Darned",
  "Dauntless",
  "Daylong",
  "Calm",
  "Capable",
  "Careful",
  "Careless",
  "Caring",
  "Cautious",
  "Charming",
  "Cheap",
  "Cheerful",
  "Chubby",
  "Clean",
  "Clever",
  "Clumsy",
  "Cold",
  "Colorful",
  "Comfortable",
  "Concerned",
  "Confused",
  "Crowded",
  "Cruel",
  "Curious",
  "Curly",
  "Cute",
  "Bad",
  "Bashful",
  "Beautiful",
  "Belligerent",
  "Beneficial",
  "Best",
  "Big",
  "Bitter",
  "Bizarre",
  "Black",
  "Blue",
  "Boring",
  "Brainy",
  "Bright",
  "Broad",
  "Broken",
  "Busy",
  "Barren",
  "Barricaded",
  "Barytic",
  "Basal",
  "Basaltic",
  "Baseborn",
  "Based",
  "Baseless",
  "Basic",
  "Bathyal",
  "Battleful",
  "Battlemented",
  "Batty",
  "Batwing",
  "Bias",
  "Abundant",
  "Accurate",
  "Addicted",
  "Adorable",
  "Adventurous",
  "Afraid",
  "Aggressive",
  "Alcoholic",
  "Alert",
  "Aloof",
  "Ambitious",
  "Ancient",
  "Angry",
  "Animated",
  "Annoying",
  "Anxious",
  "Arrogant",
  "Ashamed",
  "Attractive",
  "Auspicious",
  "Awesome",
  "Awful",
  "Abactinal",
  "Abandoned",
  "Abashed",
  "Abatable",
  "Abatic",
  "Abaxial",
  "Abbatial",
  "Abbreviated",
  "Abducent",
  "Abducting",
  "Aberrant",
  "Abeyant",
  "Abhorrent",
  "Abiding",
  "Abient",
]

const animals = [
  "Aardvark",
  "Aardwolf",
  "African Elephant",
  "African Tree Pangolin",
  "Alligator",
  "Alpaca",
  "Anteater",
  "Antelope",
  "Ape",
  "Arabian Horse",
  "Armadillo",
  "Arthropod",
  "Asian Elephant",
  "Aye-Aye",
  "Baboon",
  "Badger",
  "Bandicoot",
  "Bangle Tiger",
  "Bat",
  "Bearded Dragon",
  "Beaver",
  "Beluga Whale",
  "Bengal Tiger",
  "Big-Horned Sheep",
  "Billy Goat",
  "Bird",
  "Bison",
  "Black Bear",
  "Black Footed Rhino",
  "Black Howler Monkey",
  "Black Rhino",
  "Blacktip Reef Shark",
  "Blue Shark",
  "Blue Whale",
  "Boar",
  "Bob-Cat",
  "Bonobo",
  "Bottlenose Dolphin",
  "Bottlenose Whale",
  "Brown Bear",
  "Buffalo",
  "Bull",
  "Bull frog",
  "Caiman Lizard",
  "Camel",
  "Capuchin Monkey",
  "Capybara",
  "Caribou",
  "Cat",
  "Cattle",
  "Cheetah",
  "Chimpanzee",
  "Chinchilla",
  "Chipmunk",
  "Common Dolphin",
  "Common Seal",
  "Coral and Anemone",
  "Cougar",
  "Cow",
  "Coyote",
  "Crocodile",
  "Crustacean",
  "Dart Frog",
  "Deer",
  "Degus",
  "Dik-Dik",
  "Dingo",
  "Dog",
  "Dogfish Shark",
  "Dolphin",
  "Donkey",
  "Door Mouse",
  "Dormouse",
  "Draft Horse",
  "Duckbill Platypus",
  "Dugong",
  "Dusky Shark",
  "Elephant",
  "Elephant Seal",
  "Elk",
  "Ermine",
  "Eurasian Lynx",
  "Ferret",
  "Fish",
  "Florida Panther",
  "Flying Fox",
  "Fox",
  "Fresh Water Crocodile",
  "Frog",
  "Fur Seal",
  "Galapagos Land Iguana",
  "Galapagos Shark",
  "Galapagos Tortoise",
  "Gazelle",
  "Gecko",
  "Giant Anteater",
  "Giant Panda",
  "Gibbon",
  "Giraffe",
  "Goat",
  "Gopher",
  "Gorilla",
  "Gray Fox",
  "Gray Nurse Shark",
  "Gray Reef Shark",
  "Gray Whale",
  "Great White Shark",
  "Green Poison Dart Frog",
  "Green Sea Turtle",
  "Grizzly Bear",
  "Groundhog",
  "Guinea Pig",
  "Hairy-Nosed Wombat",
  "Hammerhead Shark",
  "Harbor Porpoise",
  "Harbor Seal",
  "Hare",
  "Harp Seal",
  "Hawaiian Monk Seal",
  "Hedgehog",
  "Hippopotamus",
  "Horn Shark",
  "Horse",
  "Howler Monkey",
  "Humpback Whale",
  "Hyena",
  "Hyrax",
  "Iguana",
  "Iguanodon",
  "Impala",
  "Insect",
  "Irrawaddy Dolphin",
  "Jackal",
  "Jackrabbit",
  "Jaguar",
  "Jellyfish",
  "Kangaroo",
  "Kermode Bear",
  "Killer Whale",
  "Koala",
  "Komodo Dragon",
  "Kookaburra",
  "Lama",
  "Lamb",
  "Lancelet",
  "Least Weasel",
  "Leatherback Sea Turtle",
  "Lemming",
  "Lemon Shark",
  "Lemur",
  "Leopard",
  "Leopard Gecko",
  "Leopard Seal",
  "Leopard Shark",
  "Lion",
  "Llama",
  "Loggerhead Turtles",
  "Lynx",
  "Mako Shark",
  "Manatee",
  "Manta Ray",
  "Mantis",
  "Marbled Salamander",
  "Marmot",
  "Marsupial",
  "Meerkat",
  "Megamouth Shark",
  "Melon-Headed Whale",
  "Miniature Donkey",
  "Mink",
  "Minke Whale",
  "Mole",
  "Mole Salamander",
  "Mollusk",
  "Mongoose",
  "Monitor Lizard",
  "Monk Seal",
  "Monkey",
  "Moose",
  "Mountain Lion",
  "Mouse",
  "Mule",
  "Muskox",
  "Muskrat",
  "Naked Mole Rat",
  "Narwhal",
  "Nautilus",
  "Newt",
  "Northern Right Whale",
  "Nurse Shark",
  "Nutria",
  "Nyala",
  "Ocelot",
  "Octopus",
  "Okapi",
  "Opossum",
  "Orangutan",
  "Orca",
  "Otter",
  "Ox",
  "Panda",
  "Panther",
  "Pig",
  "Pilot Whale",
  "Pine Marten",
  "Platypus",
  "Polar Bear",
  "Porcupine",
  "Porpoise",
  "Possum",
  "Potbellied Pig",
  "Potto",
  "Prairie Dog",
  "Proboscis Monkey",
  "Przewalski's Wild horse",
  "Puma",
  "Pygmy Hippopotamus",
  "Pygmy Right Whale",
  "Pygmy Sperm Whale",
  "Quokkas",
  "Quolls",
  "Rabbit",
  "Raccoon",
  "Rat",
  "Ray",
  "Red Fox",
  "Red Kangaroo",
  "Red Panda",
  "Red-Eyed Tree Frog",
  "Reef Shark",
  "Reindeer",
  "Rhino",
  "Rhinoceros",
  "Right Whale",
  "Ringed Seal",
  "Risso's Dolphin",
  "River Dolphin",
  "Salamander",
  "Sandbar Shark",
  "Scalloped Hammerhead Shark",
  "Sea Lion",
  "Sea Turtles",
  "Seal",
  "Sei Whale",
  "Shark",
  "Sheep",
  "Shortfin Mako Shark",
  "Siberian Tiger",
  "Silky Shark",
  "Skink",
  "Skunk",
  "Slender Loris",
  "Sloth",
  "Sloth Bear",
  "Snake",
  "Snow Fox",
  "Snow Hare",
  "Snow Leopard",
  "Snow Monkey",
  "Somali Wild Ass",
  "Spectacled Bear",
  "Sperm Whale",
  "Spider Monkey",
  "Spiny Dogfish Shark",
  "Spotted Dolphin",
  "Squirrel",
  "Star-Nosed Mole",
  "Stellar Sea Lion",
  "Striped Dolphin",
  "Sun Bear",
  "Takin",
  "Tamarin",
  "Tapir",
  "Tasmanian Devil",
  "Tasmanian Tiger",
  "Terrapin",
  "Thresher Shark",
  "Tiger",
  "Tiger Salamander",
  "Tiger Shark",
  "Topi",
  "Tortoise",
  "Tree Frog",
  "Turtle",
  "Uakari",
  "Vampire Bat",
  "Vancouver Island Marmot",
  "Vervet Monkey",
  "Vicuna",
  "Vole",
  "Wallaby",
  "Walrus",
  "Warthog",
  "Water Buffalo",
  "Weasel",
  "Whale Shark",
  "Whale",
  "White Rhino",
  "White Tailed Deer",
  "White-Beaked Dolphin",
  "Whitetip Reef Shark",
  "Wildcat",
  "Wildebeest",
  "Wobbegong Shark",
  "Wolf",
  "Wolverine",
  "Wombat",
  "Woodchuck",
  "Yak",
  "Yellow-Bellied Marmot",
  "Zebra",
  "Zebu",
  "Zorilla",
]
